<?php

/**
 * @file
 * Module hooks and utility functions.
 */

function livingstone_devel_menu() {
  return array(
    'admin/config/development/livingstone' => array(
      'title' => 'Livingstone development settings',
      'access arguments' => array('administer content'),
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('livingstone_devel_admin_form'),
    ),
  );
}

/**
 * The Livingstone development form.
 *
 * @param array $form
 *   Drupal form.
 * @param array $form_state
 *   Drupal form state.
 *
 * @return array
 *   The form definition.
 */
function livingstone_devel_admin_form(array $form, array &$form_state) {
  return array(
    'branch' => array(
      '#type' => 'select',
      '#options' => array(
        'dev' => 'dev',
        'stage' => 'stage',
        'prod' => 'prod',
      ),
    ),
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Update Modules'),
    ),
  );
}

/**
 * Performs the form submission.
 *
 * @param array $form
 *   Drupal form.
 * @param array $form_state
 *   Drupal form state.
 */
function livingstone_devel_admin_form_submit(array $form, array &$form_state) {
  $branch = $form_state['values']['branch'];
  $output_features = shell_exec("cd /var/www/html/sites/all/modules/features; git checkout ${branch}; git pull 2>&1");
  dsm($output_features, "Update Features");
  $output_theme = shell_exec("cd /var/www/html/sites/all/themes/lo; git checkout ${branch}; git pull 2>&1");
  dsm($output_theme, "Update Theme");
  $output_module = shell_exec("cd /var/www/html/sites/all/modules/custom/livingstone_online_module; git checkout ${branch}; git pull 2>&1");
  dsm($output_module, "Update Module");
  $output_cache = shell_exec("cd /var/www/html; /usr/local/bin/drush cc all 2>&1");
  dsm($output_cache, "Clear Cache");
}